export interface PrivacySection {
  heading: string;
  body: string[];
}

export const privacyPolicy = {
  en: {
    title: "GK SOUND SYSTEM Privacy Policy",
    application: "GK SOUND SYSTEM",
    developer: "GK DEV",
    updated: "September 19, 2026",
    summary: "GK SOUND SYSTEM is designed as a local Windows media player. GK DEV does not collect personal data through the application, and your local media files are not uploaded to GK DEV servers.",
    sections: [
      { heading: "1. Personal Data Collection", body: ["GK SOUND SYSTEM does not require a user account and does not collect personal information such as your name, email address, contacts, location, identifiers, or browsing activity. The application does not include advertising SDKs, usage analytics, cloud synchronization, or automatic remote telemetry."] },
      { heading: "2. Local Media Files and Library Access", body: ["The application can access audio, video, and other supported media files that you select, as well as folders or library locations that you choose to make available to the application. This access is used only to browse, index, display metadata for, play, and manage media on your device.", "Your local media files are processed on your device and are not uploaded to GK DEV servers."] },
      { heading: "3. How Data Is Used", body: ["Information handled by the application is used locally to provide media playback and related features, including library organization, playlists, playback state, DSP and sound-profile preferences, and other application settings. GK DEV does not use your local media or local application data for advertising, profiling, or marketing."] },
      { heading: "4. Local Storage and Retention", body: ["GK SOUND SYSTEM may store application settings, playlists or library metadata, playback state, DSP/profile preferences, and diagnostic log files locally on your Windows device. These items remain on the device unless you remove them. App-managed local data can be removed by clearing application data or uninstalling the application, as applicable. Files you created or saved outside the app's managed storage remain under your control."] },
      { heading: "5. Diagnostics and Crash Logs", body: ["Diagnostic and crash information generated by GK SOUND SYSTEM remains local and is not automatically transmitted to GK DEV. If you request support, you may choose to manually share diagnostic information. Any information you voluntarily provide for support is used only to investigate and respond to that support request."] },
      { heading: "6. Sharing With Third Parties", body: ["GK DEV does not sell, rent, or share personal data collected by GK SOUND SYSTEM because the application does not collect personal data. Normal Windows and Microsoft Store platform services may operate under Microsoft's own terms and privacy practices independently of GK DEV."] },
      { heading: "7. Permissions and Device Access", body: ["Any file or folder access requested by GK SOUND SYSTEM is limited to functionality needed to work with media and locations you choose. The application does not use local file access to upload your media to GK DEV servers."] },
      { heading: "8. Security", body: ["The application's local-processing design minimizes transmission of user information. GK DEV uses reasonable technical practices intended to protect app-managed data. You remain responsible for the security of your Windows account, device, and local files."] },
      { heading: "9. Children's Privacy", body: ["GK SOUND SYSTEM does not knowingly collect personal information from children. Because the application does not collect personal data through its normal operation, it does not knowingly create profiles of children or transmit their local media to GK DEV."] },
      { heading: "10. Changes to This Policy", body: ["This Privacy Policy may be updated when the application's features or privacy practices change. The latest version will be published at the stable legacy privacy-policy URL and the date above will be updated."] },
      { heading: "11. Contact", body: ["For privacy or support questions, contact GK DEV via the official Microsoft Store support/contact channel for GK SOUND SYSTEM."] }
    ]
  },
  ar: {
    title: "سياسة خصوصية GK SOUND SYSTEM",
    application: "GK SOUND SYSTEM",
    developer: "GK DEV",
    updated: "19 سبتمبر 2026",
    summary: "صُمم GK SOUND SYSTEM كمشغل وسائط محلي لنظام Windows. لا تجمع GK DEV بيانات شخصية من خلال التطبيق، ولا يتم رفع ملفات الوسائط المحلية إلى خوادم GK DEV.",
    sections: [
      { heading: "1. جمع البيانات الشخصية", body: ["لا يتطلب GK SOUND SYSTEM حساب مستخدم، ولا يجمع معلومات شخصية مثل الاسم أو البريد الإلكتروني أو جهات الاتصال أو الموقع أو المعرّفات أو نشاط التصفح. لا يتضمن التطبيق حزم إعلانات أو تحليلات استخدام أو مزامنة سحابية أو قياسًا تلقائيًا عن بُعد."] },
      { heading: "2. ملفات الوسائط المحلية والوصول إلى المكتبة", body: ["يمكن للتطبيق الوصول إلى ملفات الصوت والفيديو والوسائط المدعومة التي تختارها، وإلى المجلدات أو مواقع المكتبة التي تختار إتاحتها للتطبيق. يُستخدم هذا الوصول فقط لتصفح الوسائط وفهرستها وعرض بياناتها وتشغيلها وإدارتها على جهازك.", "تُعالج ملفات الوسائط المحلية على جهازك ولا يتم رفعها إلى خوادم GK DEV."] },
      { heading: "3. كيفية استخدام البيانات", body: ["تُستخدم المعلومات التي يتعامل معها التطبيق محليًا لتوفير تشغيل الوسائط والميزات المرتبطة به، بما في ذلك تنظيم المكتبة وقوائم التشغيل وحالة التشغيل وتفضيلات DSP والصوت والإعدادات الأخرى. لا تستخدم GK DEV وسائطك المحلية أو بيانات التطبيق المحلية للإعلانات أو إنشاء الملفات التعريفية أو التسويق."] },
      { heading: "4. التخزين المحلي والاحتفاظ بالبيانات", body: ["قد يخزن GK SOUND SYSTEM إعدادات التطبيق وقوائم التشغيل أو بيانات المكتبة الوصفية وحالة التشغيل وتفضيلات DSP أو ملفات السجل التشخيصية محليًا على جهاز Windows. تبقى هذه العناصر على الجهاز ما لم تقم بإزالتها. يمكن إزالة البيانات التي يديرها التطبيق بمسح بيانات التطبيق أو إلغاء تثبيته، حسب الحالة. وتبقى الملفات التي أنشأتها أو حفظتها خارج مساحة التطبيق تحت سيطرتك."] },
      { heading: "5. التشخيص وسجلات الأعطال", body: ["تبقى معلومات التشخيص والأعطال التي ينشئها GK SOUND SYSTEM محلية ولا تُرسل تلقائيًا إلى GK DEV. إذا طلبت الدعم، يمكنك اختيار مشاركة معلومات التشخيص يدويًا. وتُستخدم أي معلومات تقدمها طوعًا للدعم فقط للتحقيق في طلب الدعم والرد عليه."] },
      { heading: "6. المشاركة مع الأطراف الأخرى", body: ["لا تبيع GK DEV أو تؤجر أو تشارك بيانات شخصية يجمعها GK SOUND SYSTEM، لأن التطبيق لا يجمع بيانات شخصية. وقد تعمل خدمات Windows وMicrosoft Store المعتادة وفق شروط وممارسات الخصوصية الخاصة بشركة Microsoft بشكل مستقل عن GK DEV."] },
      { heading: "7. الأذونات والوصول إلى الجهاز", body: ["يقتصر أي وصول إلى الملفات أو المجلدات يطلبه GK SOUND SYSTEM على الوظائف اللازمة للعمل مع الوسائط والمواقع التي تختارها. ولا يستخدم التطبيق الوصول المحلي إلى الملفات لرفع وسائطك إلى خوادم GK DEV."] },
      { heading: "8. الأمان", body: ["يقلل تصميم المعالجة المحلية من إرسال معلومات المستخدم. تستخدم GK DEV ممارسات تقنية معقولة تهدف إلى حماية البيانات التي يديرها التطبيق. وتبقى مسؤولًا عن أمان حساب Windows وجهازك وملفاتك المحلية."] },
      { heading: "9. خصوصية الأطفال", body: ["لا يجمع GK SOUND SYSTEM معلومات شخصية من الأطفال عن علم. وبما أن التطبيق لا يجمع بيانات شخصية أثناء تشغيله المعتاد، فإنه لا ينشئ ملفات تعريف للأطفال ولا ينقل وسائطهم المحلية إلى GK DEV عن علم."] },
      { heading: "10. التغييرات على هذه السياسة", body: ["قد تُحدّث سياسة الخصوصية عند تغير ميزات التطبيق أو ممارسات الخصوصية. ستُنشر أحدث نسخة على رابط سياسة الخصوصية القديم والمستقر، وسيتم تحديث التاريخ أعلاه."] },
      { heading: "11. التواصل", body: ["لأسئلة الخصوصية أو الدعم، تواصل مع GK DEV عبر قناة الدعم أو التواصل الرسمية في Microsoft Store الخاصة بـGK SOUND SYSTEM."] }
    ]
  }
} as const;
